package xyz.fmdc.reportsender.downloader;

import javax.swing.*;
import java.awt.*;

public class Downloading extends JFrame implements Runnable {
    private JProgressBar progressBar1;
    private JPanel panel;

    @Override
    public void run() {
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Downloading");
        pack();
        setContentPane(panel);
        setLocationByPlatform(true);
        setSize(200, 100);
        setVisible(true);
    }

    public void setProgress(double d) {
        if (d == -1)
            progressBar1.setString("unknown");
        else
            progressBar1.setValue((int) (d * 100));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Downloading ReportSender...");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel.add(label1, gbc);
        progressBar1 = new JProgressBar();
        progressBar1.setStringPainted(true);
        progressBar1.setValue(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(progressBar1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
