package xyz.fmdc.reportsender;

import javax.swing.*;
import javax.swing.text.PlainDocument;
import java.awt.*;
import java.util.List;
import java.util.*;

public class Dialog extends JFrame {
    private JPanel panel;
    private JButton sendButton;
    private JButton cancelButton;
    private JTextPane textPane;
    private JCheckBox anonymous;
    private JCheckBox systemDetails;
    private JList<JCheckBox> destinationList;
    private JTextArea textArea1;
    protected DefaultListModel<JCheckBox> destinationModel;

    public Dialog() {
        $$$setupUI$$$();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Game crashed");
        pack();
        setContentPane(panel);
        setSize(600, 800);
        setLocationByPlatform(true);

        textPane.setEditable(false);

        setVisible(true);
        anonymous.addActionListener(e -> Main.updateReport(anonymous.isSelected(), systemDetails.isSelected()));
        systemDetails.addActionListener(e -> Main.updateReport(anonymous.isSelected(), systemDetails.isSelected()));
        cancelButton.addActionListener(e -> System.exit(0));
        sendButton.addActionListener(e -> {
            int s = JOptionPane.showConfirmDialog(Dialog.this, "Send the report. Are you sure?", "Verification", JOptionPane.OK_CANCEL_OPTION);
            if (s == JOptionPane.OK_OPTION) {
                List<String> disabledHookNames = new ArrayList<>();
                Enumeration<JCheckBox> elements = destinationModel.elements();
                while (elements.hasMoreElements()) {
                    JCheckBox checkBox = elements.nextElement();
                    if (!checkBox.isSelected())
                        disabledHookNames.add(checkBox.getText());
                }
                Map<String, Hook> enabledHooks = new HashMap<>(Main.hooks);
                for (String name : disabledHookNames)
                    enabledHooks.remove(name);
                Sender.send(enabledHooks);
            }
        });
    }

    public void setText(String s) {
        textPane.setText(s);
    }

    public boolean getAnonymous() {
        return anonymous.isSelected();
    }

    public boolean getSystemDetails() {
        return systemDetails.isSelected();
    }

    public String getUserInput() {
        return textArea1.getText().equals("") ? null : textArea1.getText();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setBackground(new Color(-1));
        panel.setEnabled(true);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-1));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(panel1, gbc);
        sendButton = new JButton();
        sendButton.setBackground(new Color(-1));
        sendButton.setEnabled(true);
        sendButton.setText("Send");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 0, 5, 5);
        panel1.add(sendButton, gbc);
        cancelButton = new JButton();
        cancelButton.setBackground(new Color(-1));
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 0, 5, 10);
        panel1.add(cancelButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Your game has crashed. Would you like to send a report to the developer?");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(panel2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Report to be sent:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.1;
        gbc.weighty = 0.02;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(scrollPane1, gbc);
        textPane = new JTextPane();
        textPane.setBackground(new Color(-1));
        textPane.setText("");
        scrollPane1.setViewportView(textPane);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 0.02;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel3, gbc);
        anonymous = new JCheckBox();
        anonymous.setBackground(new Color(-1));
        anonymous.setText("Hide \"Affected level / Details\"");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(anonymous, gbc);
        systemDetails = new JCheckBox();
        systemDetails.setBackground(new Color(-1));
        systemDetails.setText("Hide \"System Details\"");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(systemDetails, gbc);
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.1;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(scrollPane2, gbc);
        scrollPane2.setViewportView(destinationList);
        final JScrollPane scrollPane3 = new JScrollPane();
        scrollPane3.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(scrollPane3, gbc);
        textArea1 = new JTextArea();
        textArea1.setText("");
        scrollPane3.setViewportView(textArea1);
        final JLabel label3 = new JLabel();
        label3.setText("Situation at the time of the crash (PLEASE DO NOT WRITE PERSONAL INFORMATION!):");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private void createUIComponents() {
        destinationModel = new DefaultListModel<>();
        destinationList = new JList<>(destinationModel);
        destinationList.setBackground(Color.WHITE);
        /* CellRendererを設定する */
        CheckBoxList.CheckBoxRenderer renderer = new CheckBoxList.CheckBoxRenderer();
        destinationList.setCellRenderer(renderer);

        /* MouseListenerをセットする */
        destinationList.addMouseListener(new CheckBoxList(destinationList, destinationModel));
    }
}
